#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# if [ -z "${POSTGRES_USER}" ]; then
#     base_postgres_image_default_user='postgres'
#     export POSTGRES_USER="${base_postgres_image_default_user}"
# fi
export DATABASE_URL="postgres://postgres.xhsoxxxvhgqmjdebdtan:krakof1998..,,@aws-0-eu-central-1.pooler.supabase.com:5432/postgres"

wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo 'PostgreSQL is available'

exec "$@"
